apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PORT: "4000"
  MONGODB_URL: "mongodb://mongo-service:27017/auth"
  ACCESS_SECRET: "inna_lillahi_va_inna_ilayhi_rojiun"
  REFRESH_SECRET: "inna_lillahi_va_inna_ilayhi_rojiun"
