apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  PORT: "4000"
  MONGODB_URL: mongodb+srv://furqatbozorov:<kosonsoy>@cluster0.n80gcpf.mongodb.net/?appName=Cluster0
  ACCESS_SECRET: "ef612ad36736069a8d101ff9f5fb4976c63fda9bc76919f62f80adee7e23e652"
  REFRESH_SECRET: "37c8ebb29eb2f4b7ca4f61e0b5bedc4d09ddac23ef5c1a0df48b47b5fbfc8f2b"
